import { readFile, writeFile } from 'node:fs/promises';
import { parsePopupRule } from './popup-filter-parser.mjs';

// Each Chrome world gets ONE file with lexical dependencies. Do not rely on
// a Window/global property being shared by separate manifest script entries.
const root = new URL('../', import.meta.url);
const read = path => readFile(new URL(path, root), 'utf8');
function replaceOnce(source, from, to) {
  if (source.split(from).length !== 2) throw Error(`Bundle source changed: ${from}`);
  return source.replace(from, to);
}
const policySource = await read('general/policy.js');
const policy = replaceOnce(policySource, 'globalThis.__YAS_GENERAL_POLICY_V3__ = ', 'return ');
const siteRules = JSON.parse(await read('general/site-rules.json'));
const cosmeticPolicies = JSON.parse(await read('filters/cosmetic-policy.json'));
const popupRules = [], unsupportedPopupRules = [];
for (const source of ['easylist', 'youslist', 'focus']) for (const line of (await read(`filters/sources/${source}.txt`)).split(/\r?\n/)) {
  const rule = parsePopupRule(line);
  if (!rule) continue;
  if (rule.unsupported) unsupportedPopupRules.push({ source, ...rule }); else popupRules.push(rule);
}
await writeFile(new URL('filters/popup.json', root), JSON.stringify(popupRules));
await writeFile(new URL('filters/popup-limitations.json', root), JSON.stringify({ rules: popupRules.length, unsupported: unsupportedPopupRules }, null, 2) + '\n');
const data = replaceOnce(await read('general/rule-data.js'), 'globalThis.__YAS_GENERAL_DATA_V3__ = ', 'return ');
const hostData = JSON.parse((await read('general/rule-data.js')).split('globalThis.__YAS_GENERAL_DATA_V3__ = ')[1].split('; })();')[0]);
await writeFile(new URL('filters/popup-hosts.json', root), JSON.stringify(hostData.popupHosts));
const popupData = `const popupRules = ${JSON.stringify(popupRules)};\n`;
const header = '// Generated by scripts/build-general.mjs from local source.\n';
const prefix = `${header}(() => {\n'use strict';\nconst policy = ${policy}\n`;
let cosmetic = replaceOnce(await read('general/cosmetic.js'), '  const policy = globalThis.__YAS_GENERAL_POLICY_V3__;\n', '');
cosmetic = replaceOnce(cosmetic, '  const cosmeticPolicies = globalThis.__YAS_COSMETIC_POLICY_V3__ || [];\n', '');
cosmetic = replaceOnce(cosmetic, '(globalThis.__YAS_GENERAL_SITE_RULES_V3__ || [])', 'siteRules');
await writeFile(new URL('general/content-bundle.js', root), `${prefix}const siteRules = ${JSON.stringify(siteRules)};\nconst cosmeticPolicies = ${JSON.stringify(cosmeticPolicies)};\n${cosmetic}\n})();\n`);
let guard = replaceOnce(await read('general/popup-guard.js'), '  const policy = globalThis.__YAS_GENERAL_POLICY_V3__;\n', '');
guard = replaceOnce(guard, 'globalThis.__YAS_GENERAL_DATA_V3__.popupHosts', 'ruleData.popupHosts');
guard = replaceOnce(guard, 'globalThis.__YAS_GENERAL_POPUP_RULES_V3__ || []', 'popupRules');
await writeFile(new URL('general/main-bundle.js', root), `${prefix}const ruleData = ${data}\n${popupData}${guard}\n})();\n`);
let worker = replaceOnce(await read('general/background.js'), "importScripts('general/rule-data.js', 'general/policy.js');\n", '');
worker = replaceOnce(worker, 'globalThis.__YAS_GENERAL_POLICY_V3__', 'policy');
worker = replaceOnce(worker, 'globalThis.__YAS_GENERAL_DATA_V3__.popupHosts', 'ruleData.popupHosts');
worker = replaceOnce(worker, 'globalThis.__YAS_GENERAL_POPUP_RULES_V3__ || []', 'popupRules');
await writeFile(new URL('general/worker-bundle.js', root), `${prefix}const ruleData = ${data}\n${popupData}${worker}\n})();\n`);
// Standalone export is only for the explicitly simulated CSS fixture.
await writeFile(new URL('general/site-rules.js', root), `${header}globalThis.__YAS_GENERAL_SITE_RULES_V3__ = Object.freeze(${JSON.stringify(siteRules, null, 2)});\n`);
console.log('Built self-contained general content, MAIN and worker bundles.');
