import { writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { repositoryRoot, readJSON } from './lib/package-utils.mjs';
const { version } = await readJSON(resolve(repositoryRoot, 'manifest.json'));
const safari = await readJSON(resolve(repositoryRoot, 'safari/extension/manifest.json'));
const notes = `# AdBlock + YouTube ${version} — versão de teste\n\nAtualiza a versão pública para o código atual, com bundles independentes por ambiente, exceções oficiais de filtros visuais, regras de compatibilidade por site e diagnóstico da página no popup.\n\nO README principal é em português brasileiro. O popup e os guias de instalação estão disponíveis em português, inglês, indonésio e coreano.\n\n## Chrome\n\nBaixe youtube-auto-skip-chrome-${version}.zip, extraia a pasta youtube-auto-skip, abra chrome://extensions, ative o modo do desenvolvedor e use Carregar sem compactação. Selecione a pasta que contém manifest.json. Requer Chrome 111+ no computador. Recarregue a extensão e as páginas após atualizar.\n\n## Safari / iPhone\n\nyoutube-auto-skip-safari-${safari.version}-dev.zip contém fontes de desenvolvimento da extensão Safari. Não é um aplicativo iOS assinado ou uma IPA. A instalação no iPhone exige Mac, Xcode, assinatura própria e permissão do Safari. PiP e áudio em segundo plano ainda precisam de validação em dispositivo real.\n\nSHA256SUMS registra a integridade dos dois pacotes. As fontes correspondentes e instruções completas estão no repositório. Consulte docs/VALIDATION.md para os testes e limites desta versão.\n\nEsta é uma versão de teste. Não garante bloquear todos os anúncios nem eliminar toda espera do YouTube. Filtros regionais brasileiros/indonésios não estão incluídos. Os avisos npm das dependências do conversor são documentados; essas bibliotecas não são incluídas como código executável nos ZIPs.\n`;
await mkdir(resolve(repositoryRoot, 'build'), { recursive: true });
await writeFile(resolve(repositoryRoot, 'build/release-notes.md'), notes);
console.log(`Generated release notes for ${version}`);
